import BlogHomeBanner from "$/image/blog/blog-home-banner.jpg";
import { categoryDetailsSelection } from "../../../../../../sanity/groqd/selections/category-details";
import { postDetailsSelection } from "../../../../../../sanity/groqd/selections/post-details";
import { getCategories } from "../../../../../../sanity/queries/categories/getCategories";
import {
  getRecentPosts,
  getRecentPostsByCategoryId,
} from "../../../../../../sanity/queries/post/getRecentPosts";
import BlogOverview from "../blog-overview/blog-overview";

const BlogHomePage = async () => {
  const [latestPosts, categories] = await Promise.all([
    getRecentPosts(postDetailsSelection),
    getCategories(categoryDetailsSelection),
  ]);

  const latestPostsByCategory = await Promise.all(
    categories.map(async (category) => {
      return {
        category,
        posts: await getRecentPostsByCategoryId(
          category.id,
          postDetailsSelection,
        ),
      };
    }),
  );

  return (
    <BlogOverview
      hero={{
        banner: BlogHomeBanner,
        bannerAlt: "Blog Home Banner (Generated by Gemini)",
        title: "Exploring the tech stack",
        description:
          "Check out some of the blog posts I've written about tech and programming!",
        breadcrumbs: [{ label: "Blog", href: "/blog" }],
        categories: categories.map((category) => ({
          label: category.name,
          href: `/blog/${category.slug}`,
        })),
      }}
      sections={[
        {
          title: "Latest Posts",
          posts: latestPosts,
          variant: "featured",
        },
        ...latestPostsByCategory.map(({ category, posts }) => ({
          title: category.name,
          posts,
          url: `/blog/${category.slug}`,
        })),
      ]}
    />
  );
};

export default BlogHomePage;
