import BlogHomeBanner from "$/image/blog/blog-home-banner.jpg";
import { getLatestPosts } from "../../../sanity/queries/post/getLatestPosts";
import { getCategories } from "../../../sanity/queries/categories/getCategories";
import BlogHero from "./components/blog-hero/blog-hero";
import BlogSection from "./components/blog-section/blog-section";

const BlogPage = async () => {
  const [latestPosts, categories] = await Promise.all([
    getLatestPosts(),
    getCategories(),
  ]);

  return (
    <main className="min-h-dvh">
      <BlogHero
        banner={BlogHomeBanner}
        bannerAlt="Blog Home Banner (Generated by Gemini)"
        caption="Exploring The Tech Stack"
        description="Check out some of the blog posts I've written about tech and programming!"
        breadcrumbs={[{ label: "Blog", href: "/blog" }]}
        categories={categories.map((category) => ({
          label: category.name,
          href: `/blog/${category.slug}`,
        }))}
      />

      <div className="flex flex-col gap-4">
        <BlogSection
          title="Latest Posts"
          posts={latestPosts}
          variant="featured"
        />
      </div>
    </main>
  );
};

export default BlogPage;
